---
# tasks file for Dell-Networking.dellos-system
 - name: "Provisioning system configuration for dellos9"
   dellos9_config:
      src: dellos9_system.j2
      provider: "{{ cli }}"
   when: ansible_net_os_name == "dellos9"
#   notify: save config os9
   register: output

 - name: "Provisioning system configuration for dellos10"
   dellos10_config:
      src: dellos10_system.j2
      provider: "{{ cli }}"
   when: ansible_net_os_name == "dellos10"
#   notify: save config os10
   register: output

 - name: "Provisioning system configuration for dellos6"
   dellos6_config:
      src: dellos6_system.j2
      provider: "{{ cli }}"
   when: ansible_net_os_name == "dellos6"
#   notify: save config os6
   register: output

