---
# tasks file for dellos-system
 - name: "Provision system configuration for OS10"
   dellos10_config:
      src: dellos10_system.j2
      provider: "{{ cli }}"
   when: ansible_net_os_name == "dellos10"

 - name: "Provision system configuration for OS9"
   dellos9_config:
      src: dellos9_system.j2
      provider: "{{ cli }}"
   when: ansible_net_os_name == "dellos9"

 - name: "Provision system configuration for OS6"
   dellos6_config:
      src: dellos6_system.j2
      provider: "{{ cli }}"
   when: ansible_net_os_name == "dellos6"

