---
# tasks file for dellos6
 - name: "Generating system configuration for dellos6"
   template:
      src: dellos6_system.j2
      dest: "{{ build_dir }}/system6_{{ hostname }}.conf.part"
   when: (ansible_network_os is defined and ansible_network_os == "dellos6") and ((dellos_cfg_generate | default('False')) | bool)
#   notify: save config os6
   register: generate_output

 - name: "Provisioning system configuration for dellos6"
   dellos6_config:
      src: dellos6_system.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos6")
#   notify: save config os6
   register: output
